package com.company.oop.teamProject.command.contracts.enums;

public enum CommandType {

    CREATEMEMBER,
    CREATETEAM,
    CREATEBOARD,
    CREATEBUG,
    CREATESTORY,
    CREATEFEEDBACK,
    CREATECOMMENT,
    ADDMEMBERTOTEAM,
    SHOWALLMEMBERS,
    SHOWALLTEAMS,
    SHOWALLBOARDS,
    SHOWALLTEAMMEMBERS,
    CHANGESTORYSIZE,
    ASSIGNBUG,
    ASSIGNSTORY,
    UNASSIGNBUG,
    CHANGEBUGSTATUS,
}
